#服务端口
server.port: 8180

management:
  server.port: 8181
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint.health.show-details: never
  health:
    defaults.enabled: false
    db.enabled: false

spring:
  application.name: rbac-test
  main.banner-mode: "OFF"
  boot.admin.client:
    enabled: true
    url: http://localhost:25020
    instance.prefer-ip: true
    auto-deregistration: true

#日志
logging.level:
  root: INFO
  com.lvt4j.rbac: trace
  com.lvt4j.rbactest: trace

test-filter: false
test-interceptor: true
rbac:
  center-addr: 127.0.0.1:90